export const ADD_TO_MY_LIST='ADD_TO_MY_LIST'
export const DELETE_FROM_MY_LIST='DELETE_FROM_MY_LIST'



export const LOADING_POKEMON_START='LOADING_POKEMON_START'
export const LOADING_POKEMON_FINISH='LOADING_POKEMON_FINISH'
export const SET_DATA_SEARCH_POKEMON_NAME='SET_DATA_SEARCH_POKEMON_NAME'
export const GET_ALL_POKEMON_DATA='GET_ALL_POKEMON_DATA'
export const GET_NEXT_POKEMON_DATA='GET_NEXT_POKEMON_DATA'
export const GET_PREVIOUS_POKEMON_DATA='GET_PREVIOUS_POKEMON_DATA'

export const DETAIL_DATA_POKEMON='DETAIL_DATA_POKEMON'
